### ISSUE TITLE
"date" link breaks table

### ISSUE THREAD

**Issue by chris-ca** [billthefarmer/diary#200] opened 2022-10-14 09:12 UTC
When linking to another diary page using a `date:` link within a table, the following columns are moved to the next row, breaking the table layout.
Links not using `date:` work as expected.

![Screenshot_20221014-120718](https://user-images.githubusercontent.com/13023534/195808831-cf1547c2-f83d-458a-bdab-9f25fc3d961a.jpg)

## Markdown used in the example:
```
### Test
A   | B   | C
--- | --- | ---
Line 1: A | B | This should be in column C
Line 2: [A](10.md) | [B](date:10/10/2022) | This should be in column C
Line 3: A | B | This should be in column C
```

**Comment by uli-on** [comment] 2022-10-20 11:50
Might this be caused by your style sheet, something with `display:block` for an anchor element?

**Comment by billthefarmer** [comment] 2022-10-20 12:59
I have tested and confirmed this. I will not be able to investigate until I get back to my development system. The style system just limits images, etc to `max-width: 100%;`. The markdown view is handled by my MarkdownView  library and the markdown rendering is handled by the commonmark library with various plugins. The app only handles markdown specific to the app.

**Comment by billthefarmer** [comment] 2022-10-21 11:54
Well that was simple, there was a newline on the end of the link template for adding shared links which was used later for date links. Fixed in the next version.

![Screenshot_20221021-124419 1](https://user-images.githubusercontent.com/3448386/197189468-341cf5ae-f4ed-4a5d-8e60-5538f97a59db.png)

![Screenshot_20221021-124402 1](https://user-images.githubusercontent.com/3448386/197189588-c895231e-2ba5-4981-afce-584eb67abb5c.png)

**Comment by billthefarmer** [comment] 2022-10-22 17:22
OK, I have pushed a new version with this fix, underscore, strikethrough and an optional emoji script &ndash; https://github.com/billthefarmer/diary#emojies

**Closed** 2022-10-29 09:00 UTC
