### ISSUE TITLE
Only the last date link in a paragraph works

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/diary#137] opened 2020-05-14 17:31 UTC
Steps to reproduce:

Take a working date link, copy and paste it somewhere above that link into the same paragraph, so that you have two links in one paragraph. Try the second link. It still works. Now click the first one. It'll fail.

Diary v1.66
Android 6.01, Moto flavour
Motorola G4
Webview engine v81.0.4044.138

**Comment by billthefarmer** [comment] 2020-05-14 20:19
I can't reproduce this, tested it on two devices, one a Moto G, with this entry...
```markdown
You may put links in diary pages, so
`[DuckDuckGo](https://duckduckgo.com)` will show a link to
DuckDuckGo. Links will be followed if touched. Use the back button in
the toolbar or the navigation bar to return [Link](date:10/5/2020) to the diary page.
Links to other diary pages may either be a relative reference to the entry
file `[Sunday](25.txt)`, or use a date URI
`[Whenever](date:17/10/2017)`. Use your local convention for short
form numeric dates (UK: `dd/mm/yyyy`, US: `mm/dd/yyyy`). Use the back
button to return. The back button [Link](date:10/5/2020) may be used to retrace your path
through diary entries and external web pages. Use the **Today** button
to clear the navigation entries.
```
There are two links (`[Link](date:10/5/2020)`), and they both work identically.

**Comment by uli-on** [comment] 2020-05-14 21:39
Bill, thanks for trying. Would you please try one more thing with the code you posted and remove the returns so it really forms one big lump? That's what I meant whith "one paragraph". Thanks!

**Comment by billthefarmer** [comment] 2020-05-15 12:59
OK, got it, a greedy regular expression. That will be in the next version.

**Comment by uli-on** [comment] 2020-05-18 14:12
Thanks, Bill, much appreciated.

**Closed** 2020-05-29 11:41 UTC
