### ISSUE TITLE
Support copying video

### ISSUE THREAD

**Issue by kceiw** [billthefarmer/diary#115] opened 2019-11-24 04:33 UTC
Version 1.55

There is an option to copy images. Please add the same support for video. I would like to copy every media to the same folder.

**Comment by billthefarmer** [comment] 2019-11-24 10:48
The option to copy images was offered as an enhancement by @ialokim some time ago. It specifically excluded audio and video because of the time taken to copy potentially large files. Also you would end up with duplicate copies of large files in storage, wasting space. There's nothing stopping you moving/copying them yourself.

**Comment by yhutoo** [comment] 2019-11-27 03:29
I suggest as a workaround to "Sent to" (not "Send to */* nor "Full names to clipboard" as I wrote for issue #98; this way is more straightforward) from Total Commander (v2.91) or some more File Managers.

Tested positively Asus File Manager, MiXplorer, Xplore, Memory Zone.

Some other File Mngr didn't work.

Memory Zone use  use "file:/storage"; TC "file:///storage" (best) or "/storage"; while Diary/Add media uses "content:// and a different "path", not lasting between session in my case (Asus ZenFone 3; Android 6.0.1; Diary 1.58

I have gotten to play many videos and audios (to be played pushing a play/ pause button and with a mute button, and strip); even all in the same time; and pictures still displayed in Diary pages, without any file in Diary folders for videos or audios.

.txt files work as links.

Binary files such as pdf, doc, etc. don't work this way, as far as I tested.

These links last between Diary sessions.
I hope You will be satisfied as I am by this little workaround, since Diary is a marvellous app and the Author is very committed and generous.

Best regards

**Comment by billthefarmer** [comment] 2019-11-27 09:17
The reason why you get a `content://` Uri when you use `Add media` is becuase the default file manager or picker on your device produces Uris that the resolver I am using can't resolve to a `file:///` Uri. So the change I made was to use the `content://` Uri. However to work out what sort the file is it needs the file type, which doesn't always work, so it adds a link. `content://` Uris should be persistent if they aren't the problem is the file picker that produces them. If you have a file manager that produces Uris that work, use it for `Add media`. You should get a choice...

![Screenshot_20191127-090407 1](https://user-images.githubusercontent.com/3448386/69709947-4d1d8180-10f6-11ea-8d32-ab1eff3b4c8a.png)

**Comment by yhutoo** [comment] 2019-11-27 14:11
You are absolutely right, it works with all the choices I tested now from "Open with", but not picking from the Micro SD (content://com.android.externalstorage.documents/document/0000-0000% etc.)

Since I keep most of media on the Micro SD, I always tested that option that doesn't keep still.

Is working fine picking from TC, TC (file://url), Audio, Videos, Images, Gallery, INT storage, Music (Asus).

I didn't try picking clouds or whatever more choices, because these very ones satisfy my very modest needs.
 
Thank You again, best.

**Closed** 2019-12-05 11:05 UTC
