### ISSUE TITLE
[BUG] The videos I added to the Diary app don't play.

### ISSUE THREAD

**Issue by sargoon** [billthefarmer/diary#98] opened 2019-07-10 07:02 UTC
Hi there @billthefarmer 

Actual behavior

When I select any video through the Media option, the video I added didn't play.

How to reproduce

1. Open the Diary app.
2. Click on the ellipsis menu.
3. Select the media option and add a video.
4. And you will see that the video you added doesn't play.

• App version: 1.50 (latest)
• Operating system: Android 9.0

Recording Of The Bug
![diarybug](https://user-images.githubusercontent.com/34961616/60947512-62d20c00-a2f9-11e9-848a-5fe8c78da43a.gif)

**Comment by billthefarmer** [comment] 2019-07-10 14:41
You have not given any information about the video you are trying to play, and it is not apparent from the above video. As the correct video player appears I can only assume the video type is not supported or not accessible to the video player.

**Comment by sargoon** [comment] 2019-07-10 14:52
> 
> 
> You have not given any information about the video you are trying to play, and it is not apparent from the above video. As the correct video player appears I can only assume the video type is not supported or not accessible to the video player.

Video format is mp4, I can record a new gif if you want.

**Comment by sargoon** [comment] 2019-07-11 00:12
Hello again @billthefarmer,

![GIF-190711_030809](https://user-images.githubusercontent.com/34961616/61012991-8b094b80-a389-11e9-8309-bb958b47c5cc.gif)

Sorry for the bad quality.

**Comment by billthefarmer** [comment] 2019-07-11 14:30
I can't reproduce this. I have attached a zipped mp4 of starting Diary, adding a mp4 video and playing it in the app.

[test.zip](https://github.com/billthefarmer/diary/files/3382496/test.zip)

**Comment by sargoon** [comment] 2019-07-11 14:55
> 
> 
> I can't reproduce this. I have attached a zipped mp4 of starting Diary, adding a mp4 video and playing it in the app.
> 
> [test.zip](https://github.com/billthefarmer/diary/files/3382496/test.zip)

My Device Information:
Xiaomi Redmi Note 7
ROM: MIUI Global 10.3.6
Android Version: 9.0

It's really weird. I think the reason for this issue/bug is related to device brand, ROM or android version difference.

**Comment by billthefarmer** [comment] 2019-07-11 20:04
Mp4 files can have many formats, here is the output using [ffmpeg](https://ffmpeg.org) to convert that video to animated gif...
```shell
ffmpeg -i test.mp4 test.gif
ffmpeg version N-94270-gaf9dc02e6b Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190621
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 30.100 / 56. 30.100
  libavcodec     58. 53.101 / 58. 53.101
  libavformat    58. 28.101 / 58. 28.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 56.101 /  7. 56.101
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-07-11T14:03:52.000000Z
    com.android.version: 7.1.2
  Duration: 00:00:30.81, start: 0.000000, bitrate: 948 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 720x1280, 946 kb/s, SAR 1:1 DAR 9:16, 15.06 fps, 90k tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2019-07-11T14:03:52.000000Z
      handler_name    : VideoHandle
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> gif (native))
Press [q] to stop, [?] for help
[swscaler @ 00000168ac119680] No accelerated colorspace conversion found from yuv420p to bgr8.
Output #0, gif, to 'test.gif':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.version: 7.1.2
    encoder         : Lavf58.28.101
    Stream #0:0(eng): Video: gif, bgr8, 720x1280 [SAR 1:1 DAR 9:16], q=2-31, 200 kb/s, 15.06 fps, 100 tbn, 15.06 tbc (default)
    Metadata:
      creation_time   : 2019-07-11T14:03:52.000000Z
      handler_name    : VideoHandle
      encoder         : Lavc58.53.101 gif
frame=  215 fps=123 q=-0.0 Lsize=    3462kB time=00:00:28.83 bitrate= 983.8kbits/s dup=0 drop=249 speed=16.5x
video:3462kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000564%
```
![test](https://user-images.githubusercontent.com/3448386/61081449-2ac4e900-a41f-11e9-8aad-2576fe0f9efb.gif)

**Comment by sargoon** [comment] 2019-07-12 10:50
I can add gifs without any issue, but I can't add any videos from my device.

**Comment by billthefarmer** [comment] 2019-07-14 14:16
Well, I found the problem with an android 10 emulator...
```shell
07-14 15:02:15.475  3884  3940 E chromium: [ERROR:render_media_log.cc(27)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decoder initialization failed"}
07-14 15:02:15.480  3884  3902 E chromium: [ERROR:render_media_log.cc(27)] MediaEvent: PIPELINE_ERROR DECODER_ERROR_NOT_SUPPORTED
```
On android 9 the video appears to play, but is blank. There's not a lot I can do about that, it's down to the Chromium based [WebView](https://developer.android.com/reference/android/webkit/WebView) used by the [MarkdownView](https://github.com/billthefarmer/MarkdownView).

**Comment by sargoon** [comment] 2019-07-14 16:50
> 
> 
> Well, I found the problem with an android 10 emulator...
> 
> ```shell
> 07-14 15:02:15.475  3884  3940 E chromium: [ERROR:render_media_log.cc(27)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decoder initialization failed"}
> 07-14 15:02:15.480  3884  3902 E chromium: [ERROR:render_media_log.cc(27)] MediaEvent: PIPELINE_ERROR DECODER_ERROR_NOT_SUPPORTED
> ```
> 
> On android 9 the video appears to play, but is blank. There's not a lot I can do about that, it's down to the Chromium based [WebView](https://developer.android.com/reference/android/webkit/WebView) used by the [MarkdownView](https://github.com/billthefarmer/MarkdownView).

Yeah, as you said, there is a button to play the video, the duration of the video also appears but the screen is blank.

**Comment by yhutoo** [comment] 2019-11-20 20:01
Just for Your information:
I have the same issue in two ASUS ZenFone 3, Android 6.0.1.
Up to v1.49 the movies play; when I try any more recent version (up to v1.56) movies don't play, so I go back and keep v1.49.
Thank You for this very handy app and kindest regards.

**Comment by billthefarmer** [comment] 2019-11-23 13:07
There is an option in Developer options on LineageOS for WebView implementation, which defaults to AOSP WebView, but offers Google WebView if it is installed. Whether this option is available on factory versions of android I don't know. It may be that Google WebView is the problem.

**Comment by yhutoo** [comment] 2019-11-24 02:57
Tested v1.57, got to play 2 previously added videos, a .mp4 and a .3gp, testing disabling / enabling Android System WebView and Settings/Use browser for external links, and - but did not not work anymore - trying to add media. Doesn't playback anymore without using that "way".
Also cannot add media anymore, not even a picture. With and without Android System WebView and Use Browser, the videos (added from my external SD card) worked perfectly. Revert to v1.49 for now. Thks, best.

**Comment by billthefarmer** [comment] 2019-11-24 11:14
@yhutoo if you can play previously added videos, then I think I know what the problem is in your case. It's because the content resolver I am using can't resolve the content Uris your file picker is returning. I have made a change that should fix this. It will be in the next version.

**Comment by yhutoo** [comment] 2019-11-24 19:40
Thks.Adding to Diary a .jpg (or ..jpg) doesn't work, gets just an icon and some letters/numbers. 

If renamed .JPG (or ..JPG) in the FS before adding it works as a LNK, with a path.

Afterwards adding a "!" at the beginning works as an actual picture in Diary

(The same trick doesn't work with .pdf/.PDF files.)

**Comment by yhutoo** [comment] 2019-11-25 01:45
For what it could be worth, still in v1.49, I found a momentarily workaround:

1. Select a file in Total Commander v.2.91

2.Push (should be added with the + botton/INT CMD) "botton 122 Full names to CLPBRD"

3.Paste in Diary

4.Add:

- ! as the 1st CHAR
- [around any arbitrary descr or empty]
- () around the LNK pasted from TotCmd

It keeps the media even when closing Diary.

Here are some results:

![mp4](/storage/3C26-98DA/MR/ARCH/Subjects/HUMs/Nana/Ameze/VIDEOs/2016/WP_20160414_00_05_23_Pro.mp4)
**mp4 => OK**

![jpg](/storage/3C26-98DA/MR/ARCH/Subjects/HUMs/Nana/Ameze/Photos/2016/J-2.jpg)
**jpg => OK**

![mp3](/storage/3C26-98DA/MR/MUSIC/Amália Rodrigues/Na Esquina De Ver O Mar - Amália Rodriguez.mp3)
**mp3 => OK**

![mpg](/storage/3C26-98DA/MR/MUSIC/Leona Lewis/I See You - Leona Lewis.mpg)
**mpg => OOO**

![WAV](/storage/3C26-98DA/MR/MUSIC/SudAfrica/SA-0.WAV)
**WAV => OOO**

![wav](/storage/3C26-98DA/MR/MUSIC/SudAfrica/SA-0.wav)
 **wav => OK**

![mp4](/storage/3C26-98DA/MR/MUSIC/NIG/.AUD-20180129-Sermon-2.m4a)
**mp4 => OK**


![amr](/storage/3C26-98DA/MR/MUSIC/NIG/.AUD-20180123-Sermon.amr)
**amr => OK**

![3gp](/storage/3C26-98DA/MR/ARCH/Subjects/HUMs/Nana/Ameze/VIDEOs/2018/VID_20180125_154303.3gp)
**3gp => OK**

![mp4](/storage/3C26-98DA/MR/ARCH/Subjects/HUMs/Nana/Ameze/VIDEOs/2018/V_20180426_141435.mp4)
**mp4 => OK**

These are EGs from Diary/Add media, not lasting between Diary sessions:

![3C26-98DA:MR/ARCH/Subjects/HUMs/Nana/Ameze/VIDEOs/2018/VID_20180125_154303.3gp](content://com.android.externalstorage.documents/document/3C26-98DA%3AMR%2FARCH%2FSubjects%2FHUMs%2FNana%2FAmeze%2FVIDEOs%2F2018%2FVID_20180125_154303.3gp)
**3gp => OOO (not lasting)**


![3C26-98DA:MR/ARCH/Subjects/HUMs/Nana/Ameze/VIDEOs/2018/V_20180426_141435.mp4](content://com.android.externalstorage.documents/document/3C26-98DA%3AMR%2FARCH%2FSubjects%2FHUMs%2FNana%2FAmeze%2FVIDEOs%2F2018%2FV_20180426_141435.mp4)
**mp4 => OOO **(not lasting)**

![1533056310783.png](dc0005bc-1c8b-41b7-8356-935310bbb02b.png)
**png => OK**

Best.

**Comment by yhutoo** [comment] 2019-11-26 14:10
Tested v1.58, now I can add media, but they don't last between Diary session.
I will use the TC workaround.
Here is for Your government a copy of the test:

20191126

#Diary-1.58-still delta Add media vs. TotCmd copy LNK
---

Same file .3gp

![3C26-98DA:MR/ARCH/Subjects/HUMs/Nana/Ameze/VIDEOs/2018/VID_20180125_154303.3gp](content://com.android.externalstorage.documents/document/3C26-98DA%3AMR%2FARCH%2FSubjects%2FHUMs%2FNana%2FAmeze%2FVIDEOs%2F2018%2FVID_20180125_154303.3gp)

**Add media => OOO**
---
![](/storage/3C26-98DA/MR/ARCH/Subjects/HUMs/Nana/Ameze/VIDEOs/2018/VID_20180125_154303.3gp)

**TC => OK**

No files get copied in Diary folders.

Thank You for the jolly great work and kindest regard.

**Closed** 2019-12-05 11:07 UTC
